---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-port
  labels:
    group: deploy
data:
  HTTP_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  labels:
    group: deploy
data:
  index.html: |
    <html>
    <body>
        <h1>TestTestTest</h1>
    </body>
    </html>
...
