---
apiVersion: v1
kind: Service
metadata:
  name: multi-service
spec:
  selector:
      group: deploy
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  - name: multitool
    protocol: TCP
    port: 8080
    targetPort: 8080
...
