apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reocoker-role-binding
  namespace: default
subjects:
- kind: User
  name: reocoker
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reocoker-role
  apiGroup: rbac.authorization.k8s.io
