# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

        # machine1
        config.vm.define "machine1" do |machine1|
                machine1.vm.hostname = "machine1"
                machine1.vm.box = "hashicorpbionic64"
                machine1.vm.network "public_network", ip: "192.168.31.10"
                machine1.vm.provider "virtualbox" do |vb|
				        vb.gui = true
                        vb.customize ["modifyvm", :id, "--memory", "4096" ]
                        vb.customize ["modifyvm", :id, "--cpus", "2" ]
                        vb.customize ["modifyvm", :id, "--name", "machine1" ]
                end
                machine1.vm.provision "shell", inline: <<-SHELL
                sudo echo "192.168.31.10 machine1" | sudo tee -a /etc/hosts
                sudo echo "192.168.31.11 machine2" | sudo tee -a /etc/hosts
                sudo apt-get update
                sudo apt-get install rabbitmq-server -y
                sudo systemctl start rabbitmq-server
                sudo systemctl enable rabbitmq-server
                sudo rabbitmq-plugins enable rabbitmq_management
                sudo systemctl restart rabbitmq-server
                sudo cp /var/lib/rabbitmq/.erlang.cookie /vagrant/
                SHELL
        end


        # machine2
        config.vm.define "machine2" do |machine2|
                machine2.vm.hostname = "machine2"
                machine2.vm.box = "hashicorpbionic64"
                machine2.vm.network "public_network", ip: "192.168.31.11"
                machine2.vm.provider "virtualbox" do |vb|
				        vb.gui = true
                        vb.customize ["modifyvm", :id, "--memory", "4096" ]
                        vb.customize ["modifyvm", :id, "--cpus", "2" ]
                        vb.customize ["modifyvm", :id, "--name", "machine2" ]
                end
                machine2.vm.provision "shell", inline: <<-SHELL
                sudo echo "192.168.31.10 machine1" | sudo tee -a /etc/hosts
                sudo echo "192.168.31.11 machine2" | sudo tee -a /etc/hosts
                sudo apt-get update
                sudo apt-get install rabbitmq-server -y
                sudo systemctl start rabbitmq-server
                sudo systemctl enable rabbitmq-server
                sudo rabbitmq-plugins enable rabbitmq_management
                sudo systemctl restart rabbitmq-server
                sudo cp /vagrant/.erlang.cookie /var/lib/rabbitmq/
                sudo rm -rf /var/log/rabbitmq/*
                sudo systemctl restart rabbitmq-server
                sudo rabbitmqctl stop_app
                sudo rabbitmqctl join_cluster rabbit@machine1
                sudo rabbitmqctl start_app
                sudo rabbitmqctl set_policy ha-all ".*" '{"ha-mode":"all"}'
                sudo rabbitmqctl add_user reocoker netology
                sudo rabbitmqctl set_user_tags reocoker administrator
                sudo rabbitmqctl set_permissions -p / reocoker ".*" ".*" ".*"
                SHELL
        end
end
